/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAutoClipRouteImport } from './routes/dashboard.auto-clip'
import { Route as DashboardEditorRouteImport } from './routes/dashboard.editor'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutoClipRoute = DashboardAutoClipRouteImport.update({
  id: '/auto-clip',
  path: '/auto-clip',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditorRoute = DashboardEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/auto-clip': typeof DashboardAutoClipRoute
  '/dashboard/editor': typeof DashboardEditorRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/auto-clip': typeof DashboardAutoClipRoute
  '/dashboard/editor': typeof DashboardEditorRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/auto-clip': typeof DashboardAutoClipRoute
  '/dashboard/editor': typeof DashboardEditorRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/auto-clip'
    | '/dashboard/editor'
    | '/dashboard/history'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard/auto-clip'
    | '/dashboard/editor'
    | '/dashboard/history'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/auto-clip'
    | '/dashboard/editor'
    | '/dashboard/history'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auto-clip': {
      id: '/dashboard/auto-clip'
      path: '/auto-clip'
      fullPath: '/dashboard/auto-clip'
      preLoaderRoute: typeof DashboardAutoClipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/editor': {
      id: '/dashboard/editor'
      path: '/editor'
      fullPath: '/dashboard/editor'
      preLoaderRoute: typeof DashboardEditorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAutoClipRoute: typeof DashboardAutoClipRoute
  DashboardEditorRoute: typeof DashboardEditorRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAutoClipRoute: DashboardAutoClipRoute,
  DashboardEditorRoute: DashboardEditorRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
